version: '3.4'

services:
  gerenciadorfluxo.api:
    image: ${DOCKER_REGISTRY-}gerenciadorfluxoapi
    build:
      context: .
      dockerfile: GerenciadorFluxo.API/Dockerfile
    depends_on:
     - sqldata
  sqldata:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - MSSQL_SA_PASSWORD=Numsey#1234
      - ACCEPT_EULA=Y
    volumes:
      - c:\dados\volumes\mssql:/var/opt/mssql/data   
    ports:
      - "1450:1433"
